server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "020316"
    url: jdbc:mysql://localhost:3306/ssm_db
    type: com.alibaba.druid.pool.DruidDataSource